export * from "./searchActions";

export const CONSTANTS = {
  SEARCH_MOVIE: "SEARCH_MOVIE",
  FETCH_MOVIES: "FETCH_MOVIES",
  FETCH_MOVIE: "FETCH_MOVIE",
  SEARCH_SERIE: "SEARCH_SERIE",
  FETCH_SERIES: "FETCH_SERIES",
  FETCH_SERIE: "FETCH_SERIE",
};
